# Generated by Django 3.1.14 on 2023-11-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allsvusdwebsite', '0002_auto_20231101_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quicklinkcardinfo',
            old_name='body_text',
            new_name='text_body',
        ),
    ]
