# Generated by Django 3.1.14 on 2023-11-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsvusdwebsite', '0003_auto_20231101_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklinkcardinfo',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
