# Generated by Django 3.1.14 on 2023-11-17 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('allsvusdwebsite', '0005_auto_20231103_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='allsvusdwebsite_hello', serialize=False, to='cms.cmsplugin')),
                ('guest_name', models.CharField(default='Guest', max_length=50)),
                ('text_body', models.CharField(default='text body', max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='QuickLinkCardInfos',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='allsvusdwebsite_quicklinkcardinfos', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(null=True, upload_to='quick_link_images')),
                ('title', models.CharField(default='Title', max_length=50)),
                ('text_body', models.CharField(default='text body', max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
