# Generated by Django 3.1.14 on 2023-11-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsvusdwebsite', '0007_auto_20231116_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcardinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
