# Generated by Django 3.1.14 on 2023-11-17 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('allsvusdwebsite', '0009_auto_20231116_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventCardInfo',
        ),
    ]
