# Generated by Django 3.1.14 on 2023-11-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsvusdwebsite', '0011_eventcardinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcardinfo',
            name='date',
            field=models.CharField(default='00/00/0000', max_length=50),
        ),
        migrations.AddField(
            model_name='eventcardinfo',
            name='time',
            field=models.CharField(default='00:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventcardinfo',
            name='text_body',
            field=models.CharField(default='Text Body', max_length=500),
        ),
    ]
