# Generated by Django 3.1.14 on 2023-11-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsvusdwebsite', '0012_auto_20231116_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcardinfo',
            name='text_body',
            field=models.CharField(default='Text Body', max_length=5000),
        ),
    ]
