# Generated by Django 3.1.14 on 2023-11-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsvusdwebsite', '0014_auto_20231116_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcardinfo',
            name='link',
            field=models.TextField(default='Link to Form', max_length=5000),
        ),
    ]
