# Generated by Django 3.1.14 on 2023-11-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsvusdwebsite', '0015_eventcardinfo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcardinfo',
            name='date',
            field=models.CharField(blank=True, default='00/00/0000', max_length=50),
        ),
    ]
