# Generated by Django 3.1.14 on 2023-11-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsvusdwebsite', '0018_auto_20231120_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcardinfo',
            name='link',
            field=models.TextField(blank=True, default='Link to Form', max_length=5000),
        ),
    ]
