# Generated by Django 3.1.14 on 2023-11-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsvusdwebsite', '0019_auto_20231120_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcardinfo',
            name='link',
        ),
        migrations.AddField(
            model_name='eventcardinfo',
            name='link1',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='eventcardinfo',
            name='link2',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='eventcardinfo',
            name='link3',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
