# Generated by Django 3.1.14 on 2023-11-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsvusdwebsite', '0020_auto_20231120_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcardinfo',
            name='link1',
            field=models.TextField(blank=True, default=' ', max_length=5000),
        ),
        migrations.AlterField(
            model_name='eventcardinfo',
            name='link2',
            field=models.TextField(blank=True, default=' ', max_length=5000),
        ),
        migrations.AlterField(
            model_name='eventcardinfo',
            name='link3',
            field=models.TextField(blank=True, default=' ', max_length=5000),
        ),
    ]
