# Generated by Django 3.1.14 on 2023-11-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsvusdwebsite', '0021_auto_20231120_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcardinfo',
            name='link1',
        ),
        migrations.RemoveField(
            model_name='eventcardinfo',
            name='link2',
        ),
        migrations.RemoveField(
            model_name='eventcardinfo',
            name='link3',
        ),
        migrations.AddField(
            model_name='eventcardinfo',
            name='donate',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='eventcardinfo',
            name='suppliesfunds',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='eventcardinfo',
            name='volunteer',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
