# Generated by Django 3.1.14 on 2023-11-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allsvusdwebsite', '0022_auto_20231120_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcardinfo',
            old_name='donate',
            new_name='donate_link',
        ),
        migrations.RenameField(
            model_name='eventcardinfo',
            old_name='suppliesfunds',
            new_name='suppliesfunds_link',
        ),
        migrations.RenameField(
            model_name='eventcardinfo',
            old_name='volunteer',
            new_name='volunteer_link',
        ),
    ]
