# Generated by Django 3.1.14 on 2023-11-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsvusdwebsite', '0023_auto_20231120_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcardinfo',
            name='date',
            field=models.CharField(default='00/00/0000', max_length=500),
        ),
        migrations.AlterField(
            model_name='eventcardinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quick_link_images'),
        ),
        migrations.AlterField(
            model_name='eventcardinfo',
            name='time',
            field=models.CharField(default='00:00', max_length=500),
        ),
        migrations.AlterField(
            model_name='eventcardinfo',
            name='title',
            field=models.CharField(default='Title', max_length=500),
        ),
    ]
