# Generated by Django 3.1.14 on 2023-11-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsvusdwebsite', '0024_auto_20231120_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcardinfo',
            old_name='suppliesfunds_link',
            new_name='register_here',
        ),
        migrations.AddField(
            model_name='eventcardinfo',
            name='link1_info',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='eventcardinfo',
            name='supplies_to_org_link',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='eventcardinfo',
            name='date',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='eventcardinfo',
            name='time',
            field=models.CharField(default='', max_length=500),
        ),
    ]
