# Generated by Django 3.1.14 on 2023-11-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allsvusdwebsite', '0026_auto_20231122_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcardinfo',
            old_name='link1_info',
            new_name='link1_button_info',
        ),
        migrations.RenameField(
            model_name='eventcardinfo',
            old_name='link2_info',
            new_name='link2_button_info',
        ),
        migrations.RenameField(
            model_name='eventcardinfo',
            old_name='link3_info',
            new_name='link3_button_info',
        ),
        migrations.RenameField(
            model_name='eventcardinfo',
            old_name='link4_info',
            new_name='link4_button_info',
        ),
    ]
